title: Samwel Charles
description: Code Vs Chords
author: Samwel Charles
logo: /static/img/profile.jpg
github: https://github.com/younggeeks
about: Fullstack developer

baseurl: ""
url: "younggeeks.github.io"

disqus_shortname: disqus_VgOWny6If1
google_analytics: UA-72862926-1

share:
  twitter_username: samjunior101
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
